# Ejemplos

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Eva", 
    "edad": 20 
}

### 

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Jose", 
    "edad": 21 
}


### 

GET http://localhost:3000/api/users HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/users/6542da20c20d9ad95c739701 HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/api/users/6548f6566802ae8e19bd782b HTTP/1.1
content-type: application/json

{ 
    "nombre": "José Antonio", 
    "edad": 32 
}

###

DELETE http://localhost:3000/api/users/6544e7ced958fc237ad628ed HTTP/1.1
content-type: application/json

###

DELETE https://api-mongodb-dev-nnas.3.us-1.fl0.io/api/users/6542da20c20d9ad95c739701 HTTP/1.1
content-type: application/json

###Mongodb
POST https://api-mongodb-dev-pjrh.3.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Jose", 
    "edad": 21 
}
###
POST https://api-mongodb-dev-pjrh.3.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json
{ 
    "nombre": "Javier", 
    "edad": 20 
}
###
POST https://api-mongodb-dev-pjrh.3.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json
{ 
    "nombre": "Gerardo", 
    "edad": 24 
}
###
POST https://api-mongodb-dev-pjrh.3.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json
{ 
    "nombre": "Toni", 
    "edad": 30 
}
###
POST https://api-mongodb-dev-pjrh.3.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json
{ 
    "nombre": "Toni", 
    "edad": 30 
}
###
POST https://api-mongodb-dev-pjrh.3.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json
{ 
    "nombre": "Lavadora", 
    "edad": 24 
}
###
POST https://api-mongodb-dev-pjrh.3.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json
{ 
    "nombre": "Secadora", 
    "edad": 30 
}
###
POST https://api-mongodb-dev-pjrh.3.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json
{ 
    "nombre": "Mesa", 
    "edad": 30 
}